server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: file:///Users/suyashs/Projects/spring-cloud-config
          clone-on-start: true

management:
  endpoints:
    web:
      exposure:
        include: conditions,env,health,httptrace,info,keepalive,krypt,logfile,refresh,beans,metrics,mappings
  metrics:
    enable:
      system: true
